### ISSUE TITLE
ReferenceError: PortReachableValidationError is not defined

### ISSUE THREAD

**Issue by fmichaud** [9fv/node-is-port-reachable#1]
```
ReferenceError: PortReachableValidationError is not defined
    at Object.<anonymous> (/home/fmichaud/.node_modules/wait-for-it/node_modules/@9fv.io/is-port-reachable/lib/index.js:17:47)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/fmichaud/.node_modules/wait-for-it/lib/wait-for-it.js:11:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/fmichaud/.node_modules/wait-for-it/test/wait-for-it.test.js:12:21)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/lib/mocha.js:536:10)
    at Object.<anonymous> (/home/fmichaud/.node_modules/repeat-until-success/node_modules/mocha/bin/_mocha:582:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3

Process finished with exit code 1
```

**Comment by fmichaud** [comment]
Fixed in [v0.1.0-beta1](https://github.com/9fv/node-is-port-reachable/tree/v0.1.0-beta1).
